import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import StoreProvider from './StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-full">
        <main
          className={`flex h-screen flex-col items-center justify-between p-24 w-screen	 ${inter.className}`}
        >
          <StoreProvider>{children}</StoreProvider>
        </main>
      </body>
    </html>
  );
}
